CREATE DATABASE HotelDB;
GO
USE HotelDB;
GO

CREATE TABLE RoomTypes (
    Id INT IDENTITY PRIMARY KEY,
    TypeName NVARCHAR(50) NOT NULL,
    Capacity INT NOT NULL CHECK (Capacity > 0)
);

CREATE TABLE Rooms (
    Id INT IDENTITY PRIMARY KEY,
    RoomNumber NVARCHAR(20) NOT NULL UNIQUE,
    RoomTypeId INT NOT NULL REFERENCES RoomTypes(Id),
    PricePerNight DECIMAL(12,2) NOT NULL CHECK (PricePerNight >= 0),
    IsAvailable BIT NOT NULL DEFAULT 1
);

CREATE TABLE Customers (
    Id INT IDENTITY PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(20),
    Email NVARCHAR(254),
    Address NVARCHAR(250)
);

CREATE TABLE Bookings (
    Id INT IDENTITY PRIMARY KEY,
    CustomerId INT NOT NULL REFERENCES Customers(Id),
    RoomId INT NOT NULL REFERENCES Rooms(Id),
    BookingDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE NOT NULL,
    CHECK (CheckOutDate > CheckInDate)
);

CREATE TABLE CheckIns (
    Id INT IDENTITY PRIMARY KEY,
    BookingId INT NOT NULL UNIQUE REFERENCES Bookings(Id),
    CheckInDateTime DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE CheckOuts (
    Id INT IDENTITY PRIMARY KEY,
    CheckInId INT NOT NULL UNIQUE REFERENCES CheckIns(Id),
    CheckOutDateTime DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE Bills (
    Id INT IDENTITY PRIMARY KEY,
    BookingId INT NOT NULL UNIQUE REFERENCES Bookings(Id),
    BillDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    TotalAmount DECIMAL(12,2) NOT NULL CHECK (TotalAmount >= 0),
    IsPaid BIT NOT NULL DEFAULT 0
);